### ISSUE TITLE
Question about 500Hz Maximum PWM Frequency

### ISSUE THREAD

**Issue by tonysmith55** [khoih-prog/ESP32_PWM#2]
Hello,  Thanks for creating a great library, particularly its non-blocking feature.

I understand controllers and interrupt driven timers but don't have experience with the ESP32 family to fully understand its features and limitations. 

Do you see a problem with extending the maximum frequency from 500Hz to 1,000Hz?  

My simple testing seems to suggest it works but I don't have access to an Oscilloscope at the moment to confirm both the frequency and waveform.

**Comment by khoih-prog** [comment]
Thanks for your interest in the library and nice words.
The max **500Hz** is just a **conservative** frequency to be sure there is no issue, but I think you can use up to multi 1000Hz or a little bit more w/o any issue, depending on how many PWM channels you're using.

To test using higher freq., you can modify this line [**ESP32_PWM_ISR.h**#L110](https://github.com/khoih-prog/ESP32_PWM/blob/main/src/ESP32_PWM_ISR.h#L110) to

```
if ( ( frequency > 0 ) )
```

from

```
if ( ( frequency > 0 ) && ( frequency <= 500 ) )
```

Having fun testing,
