### ISSUE TITLE
tried to compile the simple array example

### ISSUE THREAD

**Issue by rauber-hotzenplotz** [khoih-prog/ESP32_PWM#3]
i get this error....

> In file included from C:\Users\Fahr Radl\Documents\Arduino\esp32pwm\esp32pwm.ino:33:0:
C:\Users\Fahr Radl\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.h: In member function 'bool ESP32TimerInterrupt::setFrequency(float, esp32_timer_callback)':
C:\Users\Fahr Radl\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.h:296:100: error: 'timer_isr_callback_add' was not declared in this scope
         timer_isr_callback_add(_timerGroup, _timerIndex, _callback, (void *) (uint32_t) _timerNo, 0);
                                                                                                    ^
C:\Users\Fahr Radl\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.h: In member function 'void ESP32TimerInterrupt::detachInterrupt()':
C:\Users\Fahr Radl\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.h:338:66: error: 'TIMER_INTR_T0' was not declared in this scope
       timer_group_intr_disable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                  ^
C:\Users\Fahr Radl\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.h:338:82: error: 'TIMER_INTR_T1' was not declared in this scope
       timer_group_intr_disable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                                  ^
C:\Users\Fahr Radl\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.h: In member function 'void ESP32TimerInterrupt::disableTimer()':
C:\Users\Fahr Radl\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.h:347:66: error: 'TIMER_INTR_T0' was not declared in this scope
       timer_group_intr_disable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                  ^
C:\Users\Fahr Radl\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.h:347:82: error: 'TIMER_INTR_T1' was not declared in this scope
       timer_group_intr_disable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                                  ^
C:\Users\Fahr Radl\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.h: In member function 'void ESP32TimerInterrupt::reattachInterrupt()':
C:\Users\Fahr Radl\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.h:357:65: error: 'TIMER_INTR_T0' was not declared in this scope
       timer_group_intr_enable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                 ^
C:\Users\Fahr Radl\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.h:357:81: error: 'TIMER_INTR_T1' was not declared in this scope
       timer_group_intr_enable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                                 ^
C:\Users\Fahr Radl\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.h: In member function 'void ESP32TimerInterrupt::enableTimer()':
C:\Users\Fahr Radl\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.h:367:65: error: 'TIMER_INTR_T0' was not declared in this scope
       timer_group_intr_enable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                 ^
C:\Users\Fahr Radl\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.h:367:81: error: 'TIMER_INTR_T1' was not declared in this scope
       timer_group_intr_enable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                                 ^
exit status 1
Error compiling for board ESP32 Dev Module.

>

**Comment by khoih-prog** [comment]
![Selection_087](https://user-images.githubusercontent.com/57012152/146658936-d5cf5ad2-6523-47e6-92a5-1dd1ced72d44.png)

I compile without any problem. Have a look at [**Prerequisites**](https://github.com/khoih-prog/ESP32_PWM#prerequisites) and be sure to install the correct ESP32 core v2.0.1

Also have to follow the instruction to post issue, such as Arduino IDE and core version you're using, otherwise, the issue won't be answer next time.
