### ISSUE TITLE
V1.3 Example compiling fails

### ISSUE THREAD

**Issue by renatoa** [khoih-prog/ESP32_PWM#4]
### Describe the bug

As the title says...

### Steps to Reproduce

Just load ...\Arduino\libraries\ESP32_PWM-main\examples\ISR_Changing_PWM example and try to compile.

### Screenshots

In file included from C:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.hpp:417:0,
                 from C:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.h:44,
                 from D:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM-main\examples\ISR_Changing_PWM\ISR_Changing_PWM.ino:40:
C:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM_ISR.hpp:97:4: warning: #warning Using default CHANGING_PWM_END_OF_CYCLE == true [-Wcpp]
   #warning Using default CHANGING_PWM_END_OF_CYCLE == true
    ^
In file included from C:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.h:44:0,
                 from D:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM-main\examples\ISR_Changing_PWM\ISR_Changing_PWM.ino:40:
C:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.hpp: In member function 'bool ESP32TimerInterrupt::setFrequency(const float&, esp32_timer_callback)':
C:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.hpp:317:100: error: 'timer_isr_callback_add' was not declared in this scope
         timer_isr_callback_add(_timerGroup, _timerIndex, _callback, (void *) (uint32_t) _timerNo, 0);
                                                                                                    ^
C:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.hpp: In member function 'void ESP32TimerInterrupt::detachInterrupt()':
C:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.hpp:359:66: error: 'TIMER_INTR_T0' was not declared in this scope
       timer_group_intr_disable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                  ^
C:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.hpp:359:82: error: 'TIMER_INTR_T1' was not declared in this scope
       timer_group_intr_disable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                                  ^
C:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.hpp: In member function 'void ESP32TimerInterrupt::disableTimer()':
C:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.hpp:368:66: error: 'TIMER_INTR_T0' was not declared in this scope
       timer_group_intr_disable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                  ^
C:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.hpp:368:82: error: 'TIMER_INTR_T1' was not declared in this scope
       timer_group_intr_disable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                                  ^
C:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.hpp: In member function 'void ESP32TimerInterrupt::reattachInterrupt()':
C:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.hpp:378:65: error: 'TIMER_INTR_T0' was not declared in this scope
       timer_group_intr_enable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                 ^
C:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.hpp:378:81: error: 'TIMER_INTR_T1' was not declared in this scope
       timer_group_intr_enable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                                 ^
C:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.hpp: In member function 'void ESP32TimerInterrupt::enableTimer()':
C:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.hpp:388:65: error: 'TIMER_INTR_T0' was not declared in this scope
       timer_group_intr_enable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                 ^
C:\Users\Renato\Documents\Arduino\libraries\ESP32_PWM\src/ESP32_PWM.hpp:388:81: error: 'TIMER_INTR_T1' was not declared in this scope
       timer_group_intr_enable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                                 ^
exit status 1
Error compiling for board DOIT ESP32 DEVKIT V1.

### Information

* Arduino IDE version 1.8.13
board DOIT ESP32 DEVKIT V1.
OS: Windows 7

**Comment by khoih-prog** [comment]
Thanks for your interest in the library and your effort to post the issue.

There must be some issue with your installation and I'm not interested in helping you out. Just post on some forum to ask for basic help in installation / test.

The example is compiled and running OK for both `ESP32_DEV` and `DOIT ESP32 DEVKIT V1`

Good Luck,

![Selection_106](https://user-images.githubusercontent.com/57012152/154977438-150dae45-a587-491d-93fb-1b36641b28c9.png)

![Selection_107](https://user-images.githubusercontent.com/57012152/154977662-6d4507a1-922b-41c9-aa27-29d1b5c4d8a1.png)

**Comment by renatoa** [comment]
My installation is ok, works perfectly for mine and others code.
What is not ok is you and your attitude... and your code of course.
You already lied for the ESP8266 version of this piece of shit, making claims that anyone knows are fake, that the timer is not interrupted by wifi activity. It is any can’t be solved by software !
Better remove this absurdity from github before you fire anyone house trying to start your defective work...
