### ISSUE TITLE
Could pwmDuty be given in microseconds instead of milliseconds? I need sub-millisecond duty cycles.

### ISSUE THREAD

**Issue by tomryan2** [khoih-prog/ESP32_PWM#5]

**Comment by khoih-prog** [comment]
Hi @tomryan2 

It's totally possible. Please go thru the examples and find out by yourself.

For example https://github.com/khoih-prog/ESP32_PWM/blob/a2def1850155c311d6e21686d3243eeb5beac458/examples/ISR_Modify_PWM/ISR_Modify_PWM.ino#L73-L86



Good Luck,
