### ISSUE TITLE
Adafruit_NeoPixel.h 

### ISSUE THREAD

**Issue by tripod2** [khoih-prog/ESP32_PWM#6]
as soon pixels.show(); i get the console message : E (37150) rmt: rmt_write_items(1117): RMT DRIVER ERR
is a way to avoid conflict ?
not found any script for no lib ws2811 adressable rgb led
seem this exemple use all of the channel but im needing only 2 for L298N h-bridge 
also i need esp_now.h that seem not conflicting with ESP32_PWM.h

### Steps to Reproduce

Steps to reproduce the behavior. Including the [MRE](https://stackoverflow.com/help/minimal-reproducible-example) sketches

### Information

Please ensure to specify the following:

* Arduino IDE version (e.g. 1.8.13) or Platform.io version
* `ESP8266`,`ESP32` or `STM32` Core Version (e.g. ESP8266 core v2.7.4, ESP32 v1.0.5 or STM32 v1.9.0)
* Contextual information (e.g. what you were trying to achieve)
* Simplest possible steps to reproduce
* Anything that might be relevant in your opinion, such as:
  * Operating system (Windows, Ubuntu, etc.) and the output of `uname -a`
  * Network configuration
  
### Example

```
Arduino IDE version: 1.8.13
ESP32 Core Version 1.0.5
OS: Ubuntu 20.04 LTS
Linux xy-Inspiron-3593 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Context:
I encountered an endless loop while trying to connect to Local WiFi.

Steps to reproduce:
1. ...
2. ...
3. ...
4. ...
```

**Comment by khoih-prog** [comment]
Without any full code or [**Minimal, Reproducible Example**](https://stackoverflow.com/help/minimal-reproducible-example), no one can help you here.

I suggest you post on **Arduino**, especially **Adafruit** Forum or any other, certainly with **all necessary info**, to ask for help.

I'm closing this issue now and won't reopen until you prove this is a **bug** of this library.

Keep posting non-sense, time-wasting, vague and not actionable issues like this will get you **blocked** accessing to this library.

Good Luck,

**Comment by tripod2** [comment]
/*
 ttgo t18 v3.0 t-energy 18650
To get your voltage just analogRead pin 35. Simple math and you get the read voltage.
The included divider is set to give you half battery voltage. Whatever the ADC puts out, multiply by 2.

  ISR_Changing_PWM.ino
  For ESP32, ESP32_S2, ESP32_S3, ESP32_C3 boards with ESP32 core v2.0.0+
  Written by Khoi Hoang
  Built by Khoi Hoang https://github.com/khoih-prog/ESP32_PWM
  Licensed under MIT license

  The ESP32, ESP32_S2, ESP32_S3, ESP32_C3 have two timer groups, TIMER_GROUP_0 and TIMER_GROUP_1
  1) each group of ESP32, ESP32_S2, ESP32_S3 has two general purpose hardware timers, TIMER_0 and TIMER_1
  2) each group of ESP32_C3 has ony one general purpose hardware timer, TIMER_0
  
  All the timers are based on 64-bit counters (except 54-bit counter for ESP32_S3 counter) and 16 bit prescalers. 
  The timer counters can be configured to count up or down and support automatic reload and software reload. 
  They can also generate alarms when they reach a specific value, defined by the software. 
  The value of the counter can be read by the software program.

  Now even you use all these new 16 ISR-based timers,with their maximum interval practically unlimited (limited only by
  unsigned long miliseconds), you just consume only one ESP32-S2 timer and avoid conflicting with other cores' tasks.
  The accuracy is nearly perfect compared to software timers. The most important feature is they're ISR-based timers
  Therefore, their executions are not blocked by bad-behaving functions / tasks.
  This important feature is absolutely necessary for mission-critical tasks.
**/
//esp-32c3
//08:29:52.258 -> SCL 9
//08:29:52.399 -> SDA 8
//08:29:52.399 -> MISO 5
//08:29:52.399 -> mosi 6
//08:29:52.399 -> sck 4
//08:29:52.399 -> ss 7
#define ENA SCL
#define ENB SDA
#define IN1 SCK
#define IN2 SS
#define IN3 MOSI
#define IN4 MISO
#include <Adafruit_NeoPixel.h>
// Which pin on the Arduino is connected to the NeoPixels?
#define PIN 18 //   esp32=  4 13 16a33  //  2//esp8266 //esp01s sda 2//esp32c3 ttgo lilygo toi mini d1 plus =18
// How many NeoPixels are attached to the Arduino?
#define NUMPIXELS 8
//older NeoPixel strips  need to change the third parameter--see the strandtest
Adafruit_NeoPixel pixels = Adafruit_NeoPixel(NUMPIXELS, PIN, NEO_GRB + NEO_KHZ800);
 byte r = 0;;
  byte g = 0; 
     byte b = 0;  

#include "esp_adc_cal.h"
#define BAT_ADC    2
float Voltage = 0.0;
uint32_t readADC_Cal(int ADC_Raw);
//LilyGo-T-OI-PLUS esp32c3 16340 battery

#if !defined( ESP32 )
  #error This code is designed to run on ESP32 platform, not Arduino nor ESP8266! Please check your Tools->Board setting.
#endif

// These define's must be placed at the beginning before #include "ESP32_PWM.h"
// _PWM_LOGLEVEL_ from 0 to 4
// Don't define _PWM_LOGLEVEL_ > 0. Only for special ISR debugging only. Can hang the system.
#define _PWM_LOGLEVEL_                3

#define USING_MICROS_RESOLUTION       true    //false

// Default is true, uncomment to false
//#define CHANGING_PWM_END_OF_CYCLE     false

// To be included only in main(), .ino with setup() to avoid `Multiple Definitions` Linker Error
#include "ESP32_PWM.h"

#ifndef LED_BUILTIN
  #define LED_BUILTIN       13//LilyGo-T-OI-PLUS esp32c3 16340 battery//esp32c3 io3 //esp8266 io2

#endif

#define HW_TIMER_INTERVAL_US      20L

volatile uint32_t startMicros = 0;

// Init ESP32 timer 1
ESP32Timer ITimer(1);

// Init ESP32_ISR_PWM
ESP32_PWM ISR_PWM;

bool IRAM_ATTR TimerHandler(void * timerNo)
{
  ISR_PWM.run();

  return true;
}

//////////////////////////////////////////////////////

#define USING_PWM_FREQUENCY     true

//////////////////////////////////////////////////////

// You can assign pins here. Be carefull to select good pin to use or crash


// You can assign any interval for any timer here, in Hz
float PWM_Freq1   = 50.0f;
// You can assign any interval for any timer here, in Hz
float PWM_Freq2   = 50.0f;

// You can assign any interval for any timer here, in microseconds
uint32_t PWM_Period1 = 20000 / PWM_Freq1;
// You can assign any interval for any timer here, in microseconds
uint32_t PWM_Period2 = 20000 / PWM_Freq2;

// You can assign any duty_cycle for any PWM here, from 0-100
float PWM_DutyCycle1  = 2.0;//servo 2% to 13%
// You can assign any duty_cycle for any PWM here, from 0-100
float PWM_DutyCycle2  = 2;//%
float PWM_DutyCycle3  = 0.0;
// You can assign any duty_cycle for any PWM here, from 0-100
float PWM_DutyCycle4  = 100.0;//%

// Channel number used to identify associated channel
int channelNum;

////////////////////////////////////////////////

void setup(){
pinMode(LED_BUILTIN, OUTPUT);
pixels.begin(); // This initializes the NeoPixel library. 
// for (i = 0 ; i >= NUMPIXELS ;i ++){}
  for(int a=0; a<NUMPIXELS; a++) {pixels.setPixelColor(a, pixels.Color(30,30,30));}
    pixels.show(); // This sends the updated pixel color to the hardware.  
  pinMode(ENA, OUTPUT);
  pinMode(ENB, OUTPUT);
  pinMode(IN1, OUTPUT);
  pinMode(IN2, OUTPUT);
  pinMode(IN3, OUTPUT);
  pinMode(IN4, OUTPUT);
  Serial.begin(115200);
  while (!Serial);
  delay(2000);
  Serial.print(F("\nStarting ISR_Changing_PWM on ")); Serial.println(ARDUINO_BOARD);
  Serial.println(ESP32_PWM_VERSION);
  Serial.print(F("CPU Frequency = ")); Serial.print(F_CPU / 1000000); Serial.println(F(" MHz"));
  // Interval in microsecs
  if (ITimer.attachInterruptInterval(HW_TIMER_INTERVAL_US, TimerHandler))
  {
    startMicros = micros();
    Serial.print(F("Starting ITimer OK, micros() = ")); Serial.println(startMicros);
  }  else
    Serial.println(F("Can't set ITimer. Select another freq. or timer"));
  // Just to demonstrate, don't use too many ISR Timers if not absolutely necessary
  // You can use up to 16 timer for each ISR_PWM
  //void setPWM(uint32_t pin, uint32_t frequency, uint32_t dutycycle
  // , timer_callback_p StartCallback = nullptr, timer_callback_p StopCallback = nullptr)
}

 byte var=5;

void voltread(){
Voltage = (readADC_Cal(analogRead(BAT_ADC))) * 2;
   // Serial.printf("%.2fV", Voltage / 1000.0); // Print Voltage (in V)
//map(valeur, min_in, max_in, min_out, max_out);
int voltpixG = map(Voltage, 3000, 5000, 0, 100);
int voltpixR = map(Voltage, 3000, 5000, 255,0);
pixels.setPixelColor(var, pixels.Color(voltpixR,voltpixG,b));

switch(var){
case 0:
var=5;
break;  
case 5:
var++;
break;
case 6:
var++;
break;
case 7:
var=0;
break;
default:
break;}
pixels.setPixelColor(var, pixels.Color(30,5,20));*/
pixels.show(); // This sends the updated pixel color to the hardware.
// console spam - E (37150) rmt: rmt_write_items(1117): RMT DRIVER ERR

//while(var < 200){  something ;  var++;}
//do{ something ;} while ( var < 200);
}

const long interval = 400;           // interval at which to blink (milliseconds)
unsigned long previousMillis = 0;        // will store last time LED was updated

void loop(){
  unsigned long currentMillis = millis();
if (currentMillis - previousMillis >= interval) {    
    //previousMillis = currentMillis;
voltread();
digitalWrite(LED_BUILTIN,!digitalRead(LED_BUILTIN)); //Serial.print(" LED_BUILTIN = ");Serial.println( LED_BUILTIN );
//  Serial.print(F("Using PWM Freq = ")); Serial.print(PWM_Freq1);
//  Serial.print(F(", PWM DutyCycle = ")); Serial.println(PWM_DutyCycle1);
 joystick();
#if USING_PWM_FREQUENCY
  // You can use this with PWM_Freq in Hz
  channelNum = ISR_PWM.setPWM(ENA, PWM_Freq1, PWM_DutyCycle1);
channelNum = ISR_PWM.setPWM(ENB, PWM_Freq1, PWM_DutyCycle2);
#elif USING_MICROS_RESOLUTION
  // Or using period in microsecs resolution
  channelNum = ISR_PWM.setPWM_Period(ENA, PWM_Period1, PWM_DutyCycle1);
 channelNum = ISR_PWM.setPWM_Period(ENB, PWM_Period2, PWM_DutyCycle2);
#endif

//   int angle=map(X, 0,1023,500,2400); // on transforme la valeur analogique lue en valeur d'angle entre 0 et 180°
}}

uint32_t readADC_Cal(int ADC_Raw){
    esp_adc_cal_characteristics_t adc_chars;
    esp_adc_cal_characterize(ADC_UNIT_1, ADC_ATTEN_DB_11, ADC_WIDTH_BIT_12, 1100, &adc_chars);
    return (esp_adc_cal_raw_to_voltage(ADC_Raw, &adc_chars));
}  

void joystick(){
    // des données sur la liaison série ? (lorsque l'on appuie sur 'a' ou 'd')
    if(Serial.available())    {
         ISR_PWM.deleteChannel((uint8_t) channelNum); 
        char commande = Serial.read(); // on lit
        // on modifie la consigne si c'est un caractère qui nous intéresse
        if(commande == 'q')
            PWM_DutyCycle1 += 1;  
        else if(commande == 'a')
            PWM_DutyCycle1 -= 1; 
             else if(commande == 'w')
            PWM_DutyCycle2 += 1; 
             else if(commande == 's')
            PWM_DutyCycle2 -= 1; 
        else if(commande == '1')
            { digitalWrite(IN2,LOW);  digitalWrite(IN1,HIGH);} 
             else if(commande == '2')
         {  digitalWrite(IN1,LOW);  digitalWrite(IN2,HIGH); }
         else if(commande == '3')
            { digitalWrite(IN4,LOW);  digitalWrite(IN3,HIGH);} 
             else if(commande == '4')
         {  digitalWrite(IN3,LOW);  digitalWrite(IN4,HIGH); }
        // et on fait un retour sur la console pour savoir où on est rendu
     Serial.print("duty1= ");   Serial.print(PWM_DutyCycle1, DEC);
      Serial.print(";    duty2= ");   Serial.println(PWM_DutyCycle2, DEC);
      Serial.print("IN1= "); Serial.print(digitalRead(IN1));
      Serial.print(";    IN2= "); Serial.print(digitalRead(IN2));
      Serial.print(";    IN3= "); Serial.print(digitalRead(IN3));
      Serial.print(";    IN4= "); Serial.println(digitalRead(IN4));
    }}
 // X = analogRead(1); Serial.print("analogRead(1)=");Serial.print(analogRead(0));
  
 // Y = analogRead(2);Serial.print("analogRead(2)=");Serial.println(analogRead(1));
 /*
  * float vout = 0.0;
float vin = 0.0;
float R1 = 30000.0;  
float R2 = 7500.0; 
int value = 0;

  char volt[6] ;
void voltage(){
 value = analogRead(2);
  vout = (value * 3.3) / 1024.0; // vout = (value * 5.0) / 1024.0; //4.49v/3.15v
  vin = vout / (R2/(R1+R2));
  String str2(vin);
}

int  X = analogRead(0); Serial.print("analogRead(0)=");Serial.print(analogRead(0));
    // % (modulo) “modulo” of 5 divided by 2 is:  5 % 2 = 1
   // axisX[1] = ((X / 10) % 10) + '0';
   //x = 9 % 5;   // x now contains 4 ;
   //x = 5 % 5;   // x now contains 0
   //x = 4 % 5;   // x now contains 4
  
  */

**Comment by tripod2** [comment]
#if !defined( ESP32 )
  #error This code is designed to run on ESP32 platform, not Arduino nor ESP8266! Please check your Tools->Board setting.
#endif

// These define's must be placed at the beginning before #include "ESP32_PWM.h"
// _PWM_LOGLEVEL_ from 0 to 4
// Don't define _PWM_LOGLEVEL_ > 0. Only for special ISR debugging only. Can hang the system.
#define _PWM_LOGLEVEL_                3

#define USING_MICROS_RESOLUTION       true    //false

// Default is true, uncomment to false
//#define CHANGING_PWM_END_OF_CYCLE     false

// To be included only in main(), .ino with setup() to avoid `Multiple Definitions` Linker Error
#include "ESP32_PWM.h"

#ifndef LED_BUILTIN
  #define LED_BUILTIN       2
#endif

#define HW_TIMER_INTERVAL_US      20L

volatile uint32_t startMicros = 0;

// Init ESP32 timer 1
ESP32Timer ITimer(1);

// Init ESP32_ISR_PWM
ESP32_PWM ISR_PWM;

bool IRAM_ATTR TimerHandler(void * timerNo)
{
  ISR_PWM.run();

  return true;
}

//////////////////////////////////////////////////////

#define USING_PWM_FREQUENCY     true

//////////////////////////////////////////////////////

// You can assign pins here. Be carefull to select good pin to use or crash
uint32_t PWM_Pin    = LED_BUILTIN;

// You can assign any interval for any timer here, in Hz
float PWM_Freq1   = 100.0f;
// You can assign any interval for any timer here, in Hz
float PWM_Freq2   = 200.0f;

// You can assign any interval for any timer here, in microseconds
uint32_t PWM_Period1 = 1000000 / PWM_Freq1;
// You can assign any interval for any timer here, in microseconds
uint32_t PWM_Period2 = 1000000 / PWM_Freq2;

// You can assign any duty_cycle for any PWM here, from 0-100
float PWM_DutyCycle1  = 50.0;
// You can assign any duty_cycle for any PWM here, from 0-100
float PWM_DutyCycle2  = 90.0;

// Channel number used to identify associated channel
int channelNum;

#include <Adafruit_NeoPixel.h>
// Which pin on the Arduino is connected to the NeoPixels?
#define PIN 18 //   esp32=  4 13 16a33  //  2//esp8266 //esp01s sda 2//esp32c3 ttgo lilygo toi mini d1 plus =18
// How many NeoPixels are attached to the Arduino?
#define NUMPIXELS 8
//older NeoPixel strips  need to change the third parameter--see the strandtest
Adafruit_NeoPixel pixels = Adafruit_NeoPixel(NUMPIXELS, PIN, NEO_GRB + NEO_KHZ800);
 byte r = 0;;
  byte g = 0; 
     byte b = 0;  

void setup()
{
  Serial.begin(115200);
  while (!Serial);
pixels.begin(); // This initializes the NeoPixel library. 
// for (i = 0 ; i >= NUMPIXELS ;i ++){}
  for(int a=0; a<NUMPIXELS; a++) {pixels.setPixelColor(a, pixels.Color(30,30,30));}
    pixels.show(); // This sends the updated pixel color to the hardware.  
  delay(2000);

  Serial.print(F("\nStarting ISR_Changing_PWM on ")); Serial.println(ARDUINO_BOARD);
  Serial.println(ESP32_PWM_VERSION);
  Serial.print(F("CPU Frequency = ")); Serial.print(F_CPU / 1000000); Serial.println(F(" MHz"));

  // Interval in microsecs
  if (ITimer.attachInterruptInterval(HW_TIMER_INTERVAL_US, TimerHandler))
  {
    startMicros = micros();
    Serial.print(F("Starting ITimer OK, micros() = ")); Serial.println(startMicros);
  }
  else
    Serial.println(F("Can't set ITimer. Select another freq. or timer"));

  // Just to demonstrate, don't use too many ISR Timers if not absolutely necessary
  // You can use up to 16 timer for each ISR_PWM
  //void setPWM(uint32_t pin, uint32_t frequency, uint32_t dutycycle
  // , timer_callback_p StartCallback = nullptr, timer_callback_p StopCallback = nullptr)
}

void loop()
{
  Serial.print(F("Using PWM Freq = ")); Serial.print(PWM_Freq1); Serial.print(F(", PWM DutyCycle = ")); Serial.println(PWM_DutyCycle1);

#if USING_PWM_FREQUENCY

  // You can use this with PWM_Freq in Hz
  channelNum = ISR_PWM.setPWM(PWM_Pin, PWM_Freq1, PWM_DutyCycle1);

#else
#if USING_MICROS_RESOLUTION
  // Or using period in microsecs resolution
  channelNum = ISR_PWM.setPWM_Period(PWM_Pin, PWM_Period1, PWM_DutyCycle1);
#else
  // Or using period in millisecs resolution
  channelNum = ISR_PWM.setPWM_Period(PWM_Pin, PWM_Period1 / 1000, PWM_DutyCycle1);
#endif
#endif

  delay(10000);

  ISR_PWM.deleteChannel((uint8_t) channelNum);

  Serial.print(F("Using PWM Freq = ")); Serial.print(PWM_Freq2); Serial.print(F(", PWM DutyCycle = ")); Serial.println(PWM_DutyCycle2);

#if USING_PWM_FREQUENCY

  // You can use this with PWM_Freq in Hz
  channelNum = ISR_PWM.setPWM(PWM_Pin, PWM_Freq2, PWM_DutyCycle2);

#else
#if USING_MICROS_RESOLUTION
  // Or using period in microsecs resolution
  channelNum = ISR_PWM.setPWM_Period(PWM_Pin, PWM_Period2, PWM_DutyCycle2);
#else
  // Or using period in millisecs resolution
  channelNum = ISR_PWM.setPWM_Period(PWM_Pin, PWM_Period2 / 1000, PWM_DutyCycle2);
#endif
#endif

  delay(10000);

  ISR_PWM.deleteChannel((uint8_t) channelNum);
}

**Comment by tripod2** [comment]
THIS YOUR OWN EXEMPLE WITH ADDED THE: 
#include <Adafruit_NeoPixel.h>
// Which pin on the Arduino is connected to the NeoPixels?
#define PIN 18 // esp32= 4 13 16a33 // 2//esp8266 //esp01s sda 2//esp32c3 ttgo lilygo toi mini d1 plus =18
// How many NeoPixels are attached to the Arduino?
#define NUMPIXELS 8
//older NeoPixel strips need to change the third parameter--see the strandtest
Adafruit_NeoPixel pixels = Adafruit_NeoPixel(NUMPIXELS, PIN, NEO_GRB + NEO_KHZ800);
byte r = 0;;
byte g = 0;
byte b = 0;

void setup()
{
Serial.begin(115200);
while (!Serial);
pixels.begin(); // This initializes the NeoPixel library.
// for (i = 0 ; i >= NUMPIXELS ;i ++){}
for(int a=0; a<NUMPIXELS; a++) {pixels.setPixelColor(a, pixels.Color(30,30,30));}
pixels.show(); // This sends the updated pixel color to the hardware.
