### ISSUE TITLE
setting duty cycle to zero is not solid GND

### ISSUE THREAD

**Issue by patrikzitko** [khoih-prog/ESP32_PWM#7]
### Describe the bug
I used the ISR_16_PWMs_Array.ino and set duty cycle to zero. No matter on frequency connected LED is still partially on. It seems to me, that even set to zero, it is not solid ground.

### Steps to Reproduce

Compile ISR_16_PWMs_Array.ino with duty cycle set to zero. 

### Expected behavior

Solid logical 0

### Actual behavior

I have no osciloscope, but considering connected LED behavior, there is still duty cycle > 0 applied

### Information

* Arduino IDE version 2.0.2
* `ESP32` Core Version ESP32 core v2.0.5
* `ESP32` ESP-32 Development Board

**Comment by khoih-prog** [comment]
To have better resolution / accuracy, you have to be sure to set

https://github.com/khoih-prog/ESP32_PWM/blob/94b5557a150799c8c1a193bb1d64c8616ab2d20b/examples/ISR_16_PWMs_Array/ISR_16_PWMs_Array.ino#L35

If you've done so, check your LED circuitry to be sure it's correct.

I'm sure by using O-Scope, there is no pulse when DC = 0.

Good Luck,
